/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.Paneles;

import aplicacion.aviones.Aerolinea;
import aplicacion.usuarios.TipoSexo;
import aplicacion.vuelos.TipoAsiento;
import aplicacion.vuelos.Vuelo;
import gui.ModeloTablas.ModeloTablaEstadisticasVuelos;
import gui.VAdministrador;
import java.sql.Timestamp;

/**
 *
 * @author ruben
 */
public class PEstadisticas extends javax.swing.JPanel {

    VAdministrador va;
    
    public PEstadisticas(VAdministrador va) {
        this.va = va;
        initComponents();
        this.panelEstadisticasVuelos.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelEstadisticasVuelos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstadisticasVuelos = new javax.swing.JTable();
        dateSalidaVuelos = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtOrigenVuelos = new javax.swing.JTextField();
        txtDestinoVuelos = new javax.swing.JTextField();
        botonBuscarVuelos = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1, 1));

        tablaEstadisticasVuelos.setModel(new ModeloTablaEstadisticasVuelos(this));
        jScrollPane1.setViewportView(tablaEstadisticasVuelos);

        jLabel1.setText("Fecha Salida");

        jLabel2.setText("Origen");

        jLabel3.setText("Destino");

        txtDestinoVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestinoVuelosActionPerformed(evt);
            }
        });

        botonBuscarVuelos.setText("Buscar");
        botonBuscarVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarVuelosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEstadisticasVuelosLayout = new javax.swing.GroupLayout(panelEstadisticasVuelos);
        panelEstadisticasVuelos.setLayout(panelEstadisticasVuelosLayout);
        panelEstadisticasVuelosLayout.setHorizontalGroup(
            panelEstadisticasVuelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEstadisticasVuelosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstadisticasVuelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelEstadisticasVuelosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEstadisticasVuelosLayout.createSequentialGroup()
                        .addGroup(panelEstadisticasVuelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelEstadisticasVuelosLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtOrigenVuelos))
                            .addGroup(panelEstadisticasVuelosLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(dateSalidaVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelEstadisticasVuelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEstadisticasVuelosLayout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(botonBuscarVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelEstadisticasVuelosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDestinoVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(38, 38, 38))
        );
        panelEstadisticasVuelosLayout.setVerticalGroup(
            panelEstadisticasVuelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEstadisticasVuelosLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(panelEstadisticasVuelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtDestinoVuelos)
                    .addComponent(txtOrigenVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(panelEstadisticasVuelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEstadisticasVuelosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addComponent(botonBuscarVuelos)
                    .addComponent(dateSalidaVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        jTabbedPane1.addTab("tab1", panelEstadisticasVuelos);

        jLabel21.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("<html> <h1>Estadísticas </h1> </htlm>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarVuelosActionPerformed
        ModeloTablaEstadisticasVuelos m;
        Timestamp tSalida = null;
        if (this.dateSalidaVuelos.getDate() != null){
            tSalida = new java.sql.Timestamp(this.dateSalidaVuelos.getDate().getTime());
        }
        m=(ModeloTablaEstadisticasVuelos) this.tablaEstadisticasVuelos.getModel();
        m.setFilas(this.va.obtenerVuelos(this.txtOrigenVuelos.getText(),this.txtDestinoVuelos.getText(),tSalida));
        if (m.getRowCount() > 0) {
            this.tablaEstadisticasVuelos.setRowSelectionInterval(0, 0);
        }
    }//GEN-LAST:event_botonBuscarVuelosActionPerformed

    private void txtDestinoVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinoVuelosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinoVuelosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarVuelos;
    private com.toedter.calendar.JDateChooser dateSalidaVuelos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelEstadisticasVuelos;
    private javax.swing.JTable tablaEstadisticasVuelos;
    private javax.swing.JTextField txtDestinoVuelos;
    private javax.swing.JTextField txtOrigenVuelos;
    // End of variables declaration//GEN-END:variables

    public Aerolinea getAerolineaVuelo(Vuelo vuelo){
        return this.va.getAerolineaVuelo(vuelo);
    }
    
    public String getNacionalidadMayoritariaVuelo(Vuelo vuelo){
        return this.va.getNacionalidadMayoritariaVuelo(vuelo);
    }
    public Integer getNTipoVuelo(Vuelo vuelo,TipoAsiento ta){
        return this.va.getNTipoVuelo(vuelo,ta);
    }
    public Integer getNSexoVuelo(Vuelo vuelo, TipoSexo ts){
        return this.va.getNSexoVuelo(vuelo,ts);
    }
}
