/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author dani
 */
public class PTiendas extends javax.swing.JPanel {

    private VAdministrador va;
    private boolean primNombre;

    /**
     * Creates new form PTiendas
     */
    public PTiendas(VAdministrador va) {
        this.va  = va;
        this.primNombre = true;
        initComponents();
        this.selTerminalLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tiendasLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        terminalLabel = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        terminalComboBox = new javax.swing.JComboBox<>();
        buscarButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tiendasTable = new javax.swing.JTable();
        selTerminalLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(813, 385));

        tiendasLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiendasLabel.setText("<html>\n<h1><CENTER>Tiendas</CENTER></h1>\n</html>");

        nombreLabel.setText("Nombre: ");

        terminalLabel.setText("Terminal: ");

        nombreTextField.setText("ETSEshop");
        nombreTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreTextFieldMouseClicked(evt);
            }
        });
        nombreTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreTextFieldKeyPressed(evt);
            }
        });

        terminalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoger", "T1", "T2", "T3" }));

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        tiendasTable.setModel(new ModeloTablaTiendas());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tiendasTable, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tiendasTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );

        selTerminalLabel.setForeground(new java.awt.Color(234, 45, 45));
        selTerminalLabel.setText("¡Seleccione un número de Terminal!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tiendasLabel)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreLabel)
                            .addComponent(terminalLabel))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(terminalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(selTerminalLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buscarButton)
                                .addGap(58, 58, 58))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tiendasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(terminalLabel)
                    .addComponent(terminalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selTerminalLabel))
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreTextFieldMouseClicked
        if (this.primNombre) {
            this.nombreTextField.setText("");
            this.primNombre = false;
        }
    }//GEN-LAST:event_nombreTextFieldMouseClicked

    private void nombreTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreTextFieldKeyPressed
        if (this.primNombre) {
            this.nombreTextField.setText("");
            this.primNombre = false;
        }
    }//GEN-LAST:event_nombreTextFieldKeyPressed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        this.buscarTiendas();
    }//GEN-LAST:event_buscarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JLabel selTerminalLabel;
    private javax.swing.JComboBox<String> terminalComboBox;
    private javax.swing.JLabel terminalLabel;
    private javax.swing.JLabel tiendasLabel;
    private javax.swing.JTable tiendasTable;
    // End of variables declaration//GEN-END:variables

    public void buscarTiendas() {
        ModeloTablaTiendas m;
        m = (ModeloTablaTiendas) this.tiendasTable.getModel();
        int itemSelected = this.terminalComboBox.getSelectedIndex();
        
        if (this.primNombre) {
            if (itemSelected > 0) {
                m.setFilas(this.va.obtenerTiendas("",
                        itemSelected));
                this.selTerminalLabel.setVisible(false);
            } else {
                this.selTerminalLabel.setVisible(true);
            }
        } else {
            if (itemSelected > 0) {
                m.setFilas(this.va.obtenerTiendas(this.nombreTextField.getText(),
                        itemSelected));
                this.selTerminalLabel.setVisible(false);
            } else {
                this.selTerminalLabel.setVisible(true);
            }
        }

        if (m.getRowCount() > 0) {
            this.tiendasTable.setRowSelectionInterval(0, 0);
            // botonEliminar.setEnabled(true);
            // botonEditar.setEnabled(true);
        } else {
            // botonEliminar.setEnabled(false);
            // botonEditar.setEnabled(true);
        }
    }
}
