/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author dani
 */
public class PTiendas extends javax.swing.JPanel {

    private VAdministrador va;
    private boolean primNombre;

    /**
     * Creates new form PTiendas
     */
    public PTiendas(VAdministrador va) {
        this.va  = va;
        this.primNombre = true;
        initComponents();
        this.selTerminalLabel.setVisible(false);
        this.codigoTextField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tiendasLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        terminalLabel = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        terminalComboBox = new javax.swing.JComboBox<>();
        buscarButton = new javax.swing.JButton();
        selTerminalLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tiendasTable = new javax.swing.JTable();
        codigoLabel = new javax.swing.JLabel();
        codigoTextField = new javax.swing.JTextField();
        tipoLabel = new javax.swing.JLabel();
        tipoTextField = new javax.swing.JTextField();
        borrarButton = new javax.swing.JButton();
        anhadirButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(813, 385));

        tiendasLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiendasLabel.setText("<html>\n<h1><CENTER>Tiendas</CENTER></h1>\n</html>");

        nombreLabel.setText("Nombre: ");

        terminalLabel.setText("Terminal: ");

        nombreTextField.setText("ETSEshop");
        nombreTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreTextFieldMouseClicked(evt);
            }
        });
        nombreTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreTextFieldKeyPressed(evt);
            }
        });

        terminalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoger", "T1", "T2", "T3" }));

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        selTerminalLabel.setForeground(new java.awt.Color(234, 45, 45));
        selTerminalLabel.setText("¡Seleccione un número de Terminal!");

        tiendasTable.setModel(new ModeloTablaTiendas());
        jScrollPane1.setViewportView(tiendasTable);

        codigoLabel.setText("Código: ");

        tipoLabel.setText("Tipo: ");

        borrarButton.setText("Borrar");
        borrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarButtonActionPerformed(evt);
            }
        });

        anhadirButton.setText("Añadir");
        anhadirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anhadirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tiendasLabel)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreLabel)
                                    .addComponent(codigoLabel))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codigoTextField)
                                    .addComponent(nombreTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                                .addGap(92, 92, 92)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(selTerminalLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(buscarButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(terminalLabel)
                                            .addComponent(tipoLabel))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tipoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(terminalComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(138, 138, 138))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(borrarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(anhadirButton)))
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tiendasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarButton)
                    .addComponent(terminalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(terminalLabel)
                    .addComponent(codigoLabel)
                    .addComponent(codigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoLabel)
                    .addComponent(tipoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(selTerminalLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrarButton)
                    .addComponent(anhadirButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreTextFieldMouseClicked
        if (this.primNombre) {
            this.nombreTextField.setText("");
            this.primNombre = false;
        }
    }//GEN-LAST:event_nombreTextFieldMouseClicked

    private void nombreTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreTextFieldKeyPressed
        if (this.primNombre) {
            this.nombreTextField.setText("");
            this.primNombre = false;
        }
    }//GEN-LAST:event_nombreTextFieldKeyPressed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        this.buscarTiendas(false);
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void borrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarButtonActionPerformed
        borrar();
    }//GEN-LAST:event_borrarButtonActionPerformed

    private void anhadirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anhadirButtonActionPerformed
        anhadir();
    }//GEN-LAST:event_anhadirButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anhadirButton;
    private javax.swing.JButton borrarButton;
    private javax.swing.JButton buscarButton;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JTextField codigoTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JLabel selTerminalLabel;
    private javax.swing.JComboBox<String> terminalComboBox;
    private javax.swing.JLabel terminalLabel;
    private javax.swing.JLabel tiendasLabel;
    private javax.swing.JTable tiendasTable;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JTextField tipoTextField;
    // End of variables declaration//GEN-END:variables

    public void buscarTiendas(boolean todas) {
        ModeloTablaTiendas m;
        m = (ModeloTablaTiendas) this.tiendasTable.getModel();
        int itemSelected = this.terminalComboBox.getSelectedIndex();

        if (todas) {
            m.setFilas(this.va.obtenerTiendas("", 0));
        } else {
            if (this.primNombre) {
                if (itemSelected > 0) {
                    m.setFilas(this.va.obtenerTiendas("", itemSelected));
                    this.selTerminalLabel.setVisible(false);
                } else {
                    this.selTerminalLabel.setVisible(true);
                }
            } else {
                if (itemSelected > 0) {
                    m.setFilas(this.va.obtenerTiendas(this.nombreTextField.getText(),
                            itemSelected));
                    this.selTerminalLabel.setVisible(false);
                } else {
                    this.selTerminalLabel.setVisible(true);
                }
            }
        }

        if (m.getRowCount() > 0) {
            this.tiendasTable.setRowSelectionInterval(0, 0);
        }
    }

    private void anhadir() {
        if (!this.nombreTextField.getText().equals("")) {
            if (this.terminalComboBox.getSelectedIndex() != 0) {
                if (!this.tipoTextField.getText().equals("")) {
                    this.va.anhadirTienda(this.nombreTextField.getText(), 
                            this.terminalComboBox.getSelectedIndex(),
                            this.tipoTextField.getText());
                }
            }
        }
    }

    private void borrar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
