package gui;

import aplicacion.usuarios.Usuario;


public class VRegistrar extends javax.swing.JFrame {

        private aplicacion.FachadaAplicacion fa;

        public VRegistrar(aplicacion.FachadaAplicacion fa) {
            this.fa = fa;
        initComponents();
        this.contraDistintLabel.setVisible(false);
        this.idRepetidoLabel.setVisible(false);
        this.contraDistintLabel.setVisible(false);
        this.mensajeError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aeropuertoLabel = new javax.swing.JLabel();
        dniLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        mailLabel = new javax.swing.JLabel();
        contrasnhaLabel = new javax.swing.JLabel();
        repitPassLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        primerApellLabel = new javax.swing.JLabel();
        segunApellLabel = new javax.swing.JLabel();
        paisLabel = new javax.swing.JLabel();
        telefonLabel = new javax.swing.JLabel();
        dniTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        mailTextField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        repitPasswordField = new javax.swing.JPasswordField();
        nombreTextField = new javax.swing.JTextField();
        primApeTextField = new javax.swing.JTextField();
        segunApeTextField = new javax.swing.JTextField();
        paisTextField = new javax.swing.JTextField();
        telefonoTextField = new javax.swing.JTextField();
        dniIncorrectLabel = new javax.swing.JLabel();
        idRepetidoLabel = new javax.swing.JLabel();
        contraDistintLabel = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        mensajeError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        aeropuertoLabel.setText("<html>\n<h1>REGISTRARSE</h1>\n</html>");

        dniLabel.setText("DNI: ");

        idLabel.setText("ID: ");

        mailLabel.setText("EMAIL: ");

        contrasnhaLabel.setText("CONTRASEÑA: ");

        repitPassLabel.setText("REPETIR CONTRASEÑA: ");

        nombreLabel.setText("NOMBRE: ");

        primerApellLabel.setText("PRIMER APELLIDO: ");

        segunApellLabel.setText("SEGUNDO APELLIDO: ");

        paisLabel.setText("PAÍS: ");

        telefonLabel.setText("TELÉFONO: ");

        PasswordField.setText("Password");

        repitPasswordField.setText("Password");

        dniIncorrectLabel.setForeground(new java.awt.Color(232, 19, 19));
        dniIncorrectLabel.setText("<html>\n¡DNI incorrecto!\n</html>\n");

        idRepetidoLabel.setForeground(new java.awt.Color(226, 33, 33));
        idRepetidoLabel.setText("<html>\n¡ID repetido!\n</html>\n");

        contraDistintLabel.setForeground(new java.awt.Color(228, 27, 27));
        contraDistintLabel.setText("<html>\n<center>\n¡Las contraseñas deben <br>\nser iguales! </center>\n</html>");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        mensajeError.setForeground(new java.awt.Color(255, 0, 0));
        mensajeError.setText("El usuario no se ha podido registrar con éxito");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dniLabel)
                                    .addComponent(idLabel)
                                    .addComponent(mailLabel)
                                    .addComponent(contrasnhaLabel)
                                    .addComponent(repitPassLabel)
                                    .addComponent(nombreLabel)
                                    .addComponent(primerApellLabel)
                                    .addComponent(segunApellLabel)
                                    .addComponent(paisLabel)
                                    .addComponent(telefonLabel)
                                    .addComponent(botonCancelar))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paisTextField)
                                    .addComponent(segunApeTextField)
                                    .addComponent(primApeTextField)
                                    .addComponent(nombreTextField)
                                    .addComponent(repitPasswordField)
                                    .addComponent(PasswordField)
                                    .addComponent(telefonoTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dniTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idTextField)
                                    .addComponent(mailTextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(257, 257, 257)
                                .addComponent(aeropuertoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dniIncorrectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idRepetidoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contraDistintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(mensajeError)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aeropuertoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniLabel)
                    .addComponent(dniTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dniIncorrectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idRepetidoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mailLabel)
                    .addComponent(mailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(contrasnhaLabel)
                        .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(contraDistintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(repitPassLabel)
                    .addComponent(repitPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primerApellLabel)
                    .addComponent(primApeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(segunApellLabel)
                    .addComponent(segunApeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paisLabel)
                    .addComponent(paisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonLabel)
                    .addComponent(telefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(mensajeError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        registrarUsuario();
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel aeropuertoLabel;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JLabel contraDistintLabel;
    private javax.swing.JLabel contrasnhaLabel;
    private javax.swing.JLabel dniIncorrectLabel;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JTextField dniTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idRepetidoLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JTextField mailTextField;
    private javax.swing.JLabel mensajeError;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JLabel paisLabel;
    private javax.swing.JTextField paisTextField;
    private javax.swing.JTextField primApeTextField;
    private javax.swing.JLabel primerApellLabel;
    private javax.swing.JLabel repitPassLabel;
    private javax.swing.JPasswordField repitPasswordField;
    private javax.swing.JTextField segunApeTextField;
    private javax.swing.JLabel segunApellLabel;
    private javax.swing.JLabel telefonLabel;
    private javax.swing.JTextField telefonoTextField;
    // End of variables declaration//GEN-END:variables

    public void registrarUsuario(){
        Usuario usuario;
        
        fa.registrarUsuario(usuario);
    }
}
